export interface ArtigoMatematica {
  slug: string;
  titulo: string;
  subtitulo: string;
  emoji: string;
  cor: "pine" | "ochre" | "rust";
  nivel: "básico" | "intermediário";
  tempoLeitura: number;
  conceito: string; // nome técnico do conceito
  cotidiano: string; // gancho do cotidiano
}

export const ARTIGOS_MATEMATICA: ArtigoMatematica[] = [
  {
    slug: "combinatoria",
    titulo: "Combinatória",
    subtitulo: "Por que é impossível escolher roupa diferente todo dia por uma vida inteira",
    emoji: "🎽",
    cor: "pine",
    nivel: "básico",
    tempoLeitura: 8,
    conceito: "Combinações e permutações",
    cotidiano: "guarda-roupa, cardápio, senhas",
  },
  {
    slug: "probabilidade",
    titulo: "Probabilidade",
    subtitulo: "O que significa '50% de chance' — e por que isso não é o que parece",
    emoji: "🎲",
    cor: "ochre",
    nivel: "básico",
    tempoLeitura: 7,
    conceito: "Probabilidade clássica e frequentista",
    cotidiano: "moeda, dado, previsão do tempo",
  },
  {
    slug: "fatorial",
    titulo: "Fatorial",
    subtitulo: "O número que cresce mais rápido do que qualquer coisa que você já viu",
    emoji: "💥",
    cor: "rust",
    nivel: "básico",
    tempoLeitura: 6,
    conceito: "Fatorial e crescimento exponencial",
    cotidiano: "embaralhar baralho, senhas, filas",
  },
  {
    slug: "lei-dos-grandes-numeros",
    titulo: "Lei dos Grandes Números",
    subtitulo: "Por que o McDonald's sabe quantos hambúrgueres vender amanhã mas você não",
    emoji: "📊",
    cor: "pine",
    nivel: "básico",
    tempoLeitura: 7,
    conceito: "Lei dos Grandes Números e convergência",
    cotidiano: "produção industrial, seguro, pesquisa eleitoral",
  },
  {
    slug: "valor-esperado",
    titulo: "Valor Esperado",
    subtitulo: "A conta que toda empresa de seguro faz — e você provavelmente nunca fez",
    emoji: "⚖️",
    cor: "ochre",
    nivel: "intermediário",
    tempoLeitura: 8,
    conceito: "Esperança matemática",
    cotidiano: "seguro, investimento, loteria",
  },
  {
    slug: "media-moda-mediana",
    titulo: "Média, Moda e Mediana",
    subtitulo: "Por que a 'média salarial' pode ser completamente enganosa",
    emoji: "📏",
    cor: "rust",
    nivel: "básico",
    tempoLeitura: 6,
    conceito: "Medidas de tendência central",
    cotidiano: "salário, notas, temperatura",
  },
  {
    slug: "desvio-padrao",
    titulo: "Desvio Padrão",
    subtitulo: "O número que mede o quanto as coisas 'fogem do padrão' — e por que isso importa",
    emoji: "📉",
    cor: "pine",
    nivel: "intermediário",
    tempoLeitura: 8,
    conceito: "Variância e desvio padrão",
    cotidiano: "altura, temperatura, controle de qualidade",
  },
  {
    slug: "paradoxo-aniversario",
    titulo: "Paradoxo do Aniversário",
    subtitulo: "Em uma sala de 23 pessoas, é mais provável do que não ter dois aniversários iguais",
    emoji: "🎂",
    cor: "ochre",
    nivel: "intermediário",
    tempoLeitura: 7,
    conceito: "Probabilidade condicional e complementar",
    cotidiano: "turma de escola, time de futebol, sorteio",
  },
  {
    slug: "porcentagem",
    titulo: "Porcentagem",
    subtitulo: "Por que '50% de desconto sobre o preço com 100% de aumento' te devolve ao mesmo lugar",
    emoji: "🏷️",
    cor: "rust",
    nivel: "básico",
    tempoLeitura: 6,
    conceito: "Porcentagem, razão e proporção",
    cotidiano: "desconto, juros, inflação, imposto",
  },
  {
    slug: "distribuicao-normal",
    titulo: "Distribuição Normal",
    subtitulo: "A curva em forma de sino que governa altura, QI, erros de medição — e frequências de loteria",
    emoji: "🔔",
    cor: "pine",
    nivel: "intermediário",
    tempoLeitura: 9,
    conceito: "Distribuição gaussiana e teorema central do limite",
    cotidiano: "altura humana, notas de prova, erros industriais",
  },
  {
    slug: "juros-compostos",
    titulo: "Juros Compostos",
    subtitulo: "O segredo que bancos sabem e a maioria das pessoas ignora — e por que Einstein chamou isso de 'oitava maravilha do mundo'",
    emoji: "📈",
    cor: "ochre",
    nivel: "básico",
    tempoLeitura: 7,
    conceito: "Juros compostos e crescimento exponencial",
    cotidiano: "dívida de cartão, investimento, financiamento",
  },
  {
    slug: "logica-conjuntos",
    titulo: "Lógica e Conjuntos",
    subtitulo: "Por que 'todos os gatos são animais' não significa que 'todos os animais são gatos' — e como isso evita erros graves",
    emoji: "🔵",
    cor: "pine",
    nivel: "básico",
    tempoLeitura: 6,
    conceito: "Conjuntos, subconjuntos e lógica proposicional",
    cotidiano: "argumentação, diagnóstico médico, filtros de busca",
  },
  {
    slug: "progressoes",
    titulo: "Progressões Aritméticas e Geométricas",
    subtitulo: "Qual a diferença entre ganhar R$100 por mês e dobrar seu dinheiro todo mês — e por que ela é absurda",
    emoji: "🪜",
    cor: "rust",
    nivel: "básico",
    tempoLeitura: 7,
    conceito: "PA, PG e crescimento linear vs exponencial",
    cotidiano: "salário, investimento, viral nas redes sociais",
  },
  {
    slug: "estatistica-descritiva",
    titulo: "Estatística Descritiva",
    subtitulo: "Como resumir qualquer conjunto de dados em 5 números — e o que esses 5 números revelam que a média esconde",
    emoji: "📦",
    cor: "pine",
    nivel: "intermediário",
    tempoLeitura: 8,
    conceito: "Quartis, boxplot e resumo de cinco números",
    cotidiano: "salário, notas, tempo de entrega",
  },
  {
    slug: "correlacao-causalidade",
    titulo: "Correlação e Causalidade",
    subtitulo: "Países que comem mais chocolate ganham mais Nobel — mas isso não significa o que parece",
    emoji: "🍫",
    cor: "ochre",
    nivel: "intermediário",
    tempoLeitura: 7,
    conceito: "Correlação de Pearson e falácia da causalidade",
    cotidiano: "pesquisa científica, notícias, decisões de saúde",
  },
  {
    slug: "geometria-cotidiano",
    titulo: "Geometria no Cotidiano",
    subtitulo: "Por que uma pizza grande é quase sempre melhor negócio que duas pequenas — e a matemática que prova isso",
    emoji: "🍕",
    cor: "rust",
    nivel: "básico",
    tempoLeitura: 6,
    conceito: "Área, volume e razão de escala",
    cotidiano: "pizza, embalagem, construção, mapas",
  },
  {
    slug: "teoria-dos-jogos",
    titulo: "Teoria dos Jogos",
    subtitulo: "O dilema do prisioneiro: por que duas pessoas racionais tomam uma decisão irracional juntas",
    emoji: "🎯",
    cor: "pine",
    nivel: "intermediário",
    tempoLeitura: 8,
    conceito: "Equilíbrio de Nash e estratégias dominantes",
    cotidiano: "negociação, concorrência, dilema do prisioneiro",
  },
  {
    slug: "numeros-aleatorios",
    titulo: "O que é Aleatoriedade de Verdade",
    subtitulo: "Por que humanos são péssimos em gerar números aleatórios — e o que isso tem a ver com fraudes em loterias",
    emoji: "🎰",
    cor: "ochre",
    nivel: "intermediário",
    tempoLeitura: 7,
    conceito: "Aleatoriedade, pseudoaleatoriedade e viés cognitivo",
    cotidiano: "senha segura, sorteio, gerador de números",
  },
];

export function getArtigoMatematica(slug: string): ArtigoMatematica | undefined {
  return ARTIGOS_MATEMATICA.find((a) => a.slug === slug);
}
